# Generated by Django 4.1.5 on 2023-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg_type',
            field=models.IntegerField(max_length=10),
        ),
    ]
